SQAUTHSAML-1 Support SAML 2.0 authentication in SonarQube
SonarSource/sonar-auth-saml pull request #4
Opened 2018-07-24 14:40 UTC by julienlancelot

2018-07-26 08:53 UTC, ehartmann requested changes
Most important point is the dependencies in build.gradle.

2018-07-26 08:53 UTC, ehartmann commented on sonar-auth-saml-plugin/build.gradle
> +  compileOnly 'com.onelogin:java-saml'
There is an issue here.
If there is a dependency needed during compilation and runtime, just use `compile`.
If there is a dependency needed only during compilation (because it's provided by SonarQube), just use `compileOnly`
If the dependency is only used during runtime, just use `runtime`.

It's better to keep them ordered by usage (compileOnly, compile, runtime and testCompile).
So the correct settings is (unless servlet is provided by SonarQube) : 
```
  compile 'com.onelogin:java-saml'
  compile 'com.onelogin:java-saml-core'
  compile 'org.sonarsource.sonarqube:sonar-plugin-api'
  compile 'javax.servlet:javax.servlet-api'

  compileOnly 'com.google.code.findbugs:jsr305'

  testCompile 'org.mockito:mockito-core'
  testCompile 'org.assertj:assertj-core'
  testCompile 'junit:junit'
  testCompile 'com.tngtech.java:junit-dataprovider'
  testCompile 'javax.servlet:javax.servlet-api'
  testCompile 'org.apache.commons:commons-io'
```

2018-07-26 08:53 UTC, ehartmann commented on sonar-auth-saml-plugin/src/main/java/org/sonarsource/auth/saml/SamlIdentityProvider.java
> +  SamlIdentityProvider(SamlSettings samlSettings, boolean strictMode) {
`@VisibleForTesting` isn't missing ?
Because I'm not expecting that strictMode to never be false unless used it tests.

2018-07-26 08:53 UTC, ehartmann commented on sonar-auth-saml-plugin/src/main/java/org/sonarsource/auth/saml/SamlIdentityProvider.java
> +      throw new IllegalStateException("Fail to init", e);
I would have put a more descriptive error : "Fail to intialize SAML authentication plugin" for instance.

2018-07-26 08:53 UTC, ehartmann commented on sonar-auth-saml-plugin/src/main/java/org/sonarsource/auth/saml/SamlIdentityProvider.java
> +    samlData.put("onelogin.saml2.sp.assertion_consumer_service.url", callbackUrl != null ? callbackUrl : "http://anyurl");
It looks pretty strange to me this anyurl.

2018-07-26 08:53 UTC, ehartmann commented on sonar-auth-saml-plugin/src/main/java/org/sonarsource/auth/saml/SamlIdentityProvider.java
> +  private static String getAttribute(Auth auth, String key) {
probably a better name : `getFirstAttribute`

2018-07-26 08:53 UTC, ehartmann commented on sonar-auth-saml-plugin/src/test/resources/org/sonarsource/auth/saml/IntegrationTest/how_to_generate_test_response.txt
> +- Set the server log in TRACE
Great !!!
Probably better to use Markdown for documents.

2018-07-26 08:53 UTC, ehartmann commented on sonar-auth-saml-plugin/src/main/java/org/sonarsource/auth/saml/Cookies.java
> + * When using SonarQube 7.3 (https://jira.sonarsource.com/browse/SONAR-11072), this class should be removed
Probably adding a TODO here will add a SonarQube issue just to not forget about it.

2018-07-26 08:53 UTC, ehartmann commented on sonar-auth-saml-plugin/src/main/java/org/sonarsource/auth/saml/CsrfVerifier.java
> + * When using SonarQube 7.3 (https://jira.sonarsource.com/browse/SONAR-11072), this class should be removed
Probably adding a TODO here

2018-07-26 09:23 UTC, julienlancelot commented on sonar-auth-saml-plugin/build.gradle
> +  compileOnly 'com.onelogin:java-saml'
Thanks for the feedback! 
It was hard for me to use gradle for this plugin (first time for me :) ), so I spend a lot of time on configuration, and did not investigate too much the issue I encounter on runtime.
Your proposition is perfect !

2018-07-26 09:26 UTC, julienlancelot commented on sonar-auth-saml-plugin/src/main/java/org/sonarsource/auth/saml/SamlIdentityProvider.java
> +    samlData.put("onelogin.saml2.sp.assertion_consumer_service.url", callbackUrl != null ? callbackUrl : "http://anyurl");
The issue is coming from the OneLogin API => the most common use case for them is to use a file configuration.
The "Dynamic Settings" feature allows to not depend on a file configuration, but is not smart enough to know in which step some settings are mandatory.
In the callback, the callback URL is useless by definition, but the API does not allow to not define it.

2018-07-26 09:34 UTC, julienlancelot commented
Thanks for the feedbacks @ehartmann , I've applied them

2018-07-30 11:53 UTC, merged

2019-07-18 12:08 UTC, ricardompcarvalho commented
Hello all, I'm trying to instantiate the sonarqube in kubernetes and I need the .jar of the saml plugin, can someone help me?
Sorry for writing here but i'm desesperate. 
@julienlancelot 
@ehartmann

2019-07-18 13:03 UTC, julienlancelot commented
@ricardompcarvalho You can fin released jar of SAML plugin here : https://binaries.sonarsource.com/Distribution/sonar-auth-saml-plugin/
Do not hesitate to contact the SonarQube community forumm for any other questions : https://community.sonarsource.com/c/help/sq

2019-07-18 13:28 UTC, ricardompcarvalho commented
thank you @julienlancelot